string GenerateCSharpClass() {
    string classContent = GenerateMetadata();
    classContent += "class " + g_className + ": Alteration {\n";
    classContent += "    public override void run(Map map){\n";

    for (uint i = 0; i < g_blockInputsArray.Length; i++) {
        classContent += GenerateMethodContent(g_methodTypes[i], g_blockInputsArray[i], g_blockOutputs[i]);
    }

    classContent += "        map.placeStagedBlocks();\n";
    classContent += "    }\n";
    classContent += "}\n";

    return classContent;
}

string GenerateMethodContent(MethodType methodType, array<string> inputs, string output) {
    switch (methodType) {
        case MethodType::REPLACE:
            return GenerateReplace(inputs, output);
        case MethodType::DELETE:
            return GenerateDelete(inputs);
        case MethodType::PLACE:
            return GeneratePlace(inputs[0], output);
        case MethodType::PLACERELATIVE:
            return GeneratePlaceRelative(inputs, output);
        default:
            return "";
    }
}

string GenerateMetadata() {
    return "// Auto-generated by Alteration Helper\n"
           "// Version: " + g_version + "\n"
           "// Author: " + g_currUserName + "\n"
           "// Creation Date: " + g_creationDate + "\n"
           "// Description: " + g_description + "\n\n";
}

string GeneratePlace(string block, string newBlock) {
    return "        map.place(\"" + block + "\", \"" + newBlock + "\");\n";
}

string GeneratePlaceRelative(array<string> blocks, string newBlock, string type) { 
    string output = "";
    for (uint i = 0; i < blocks.Length; i++) {
        output += "        map.placeRelative(\"" + blocks[i] + "\", \"" + newBlock + "\", BlockType." + type + ");\n";
    }
    return output;
}

string GenerateReplace(array<string> blocks, string newBlock, string type) {
    return "        map.replace(\"" + blocks[i] + "\", \"" + newBlock + "\", BlockType."+ type +");\n";
}

string GenerateDelete(const array<string> &blocks) {
    string output = "";
    for (uint i = 0; i < blocks.Length; i++) {
        output += "        map.delete(\"" + blocks[i] + "\");\n";
    }
    return output;
}